x<-read.table("exdata_data_household_power_consumption/household_power_consumption.txt",sep = ";",header = TRUE)
x$Date<-as.Date(x$Date,"%d/%m/%Y")
y<-x[((x$Date=="2007-02-01")|(x$Date=="2007-02-02")),]
par(mfrow=c(2,2),mar=c(4,4,2,1),oma=c(0,0,0,0))
plot(as.numeric(as.character(y$Global_active_power)),type="l",ylab = "Global Active Power",xlab="",xaxt="n")
c<-c(1,nrow(y)/2,nrow(y))
b<-c("Thu","Fri","Sat")
axis(1,c,b)
plot(as.numeric(as.character(y$Voltage)),type="l",ylab = "Voltage",xlab="datetime",xaxt="n")
axis(1,c,b)
plot(as.numeric(as.character(y$Sub_metering_1)),type="l",ylab = "Energy Sub Metering",xlab="",xaxt="n")
lines(as.numeric(as.character(y$Sub_metering_2)),col="red")
lines(as.numeric(as.character(y$Sub_metering_3)),col="blue")
axis(1,c,b)
plot(as.numeric(as.character(y$Global_reactive_power)),type="l",ylab = "Global_reactive_power",xlab="datetime",xaxt="n")
axis(1,c,b)
dev.copy(png,file="plot4.png",width=480,height=480)
dev.off()